### ISSUE TITLE
mapping op Vlaamse

### ISSUE THREAD

**Issue by ghost** [tdt/ns#1]
http://ns.thedatatank.com/dcat/themes#CulturalEvents
  skos:broadMatch http://id.vlaanderen.be/vrind/concept/cultuur#id ;
.
http://ns.thedatatank.com/dcat/themes#CulturalHeritage
  skos:broadMatch http://id.vlaanderen.be/vrind/concept/cultuur#id ;
.
http://ns.thedatatank.com/dcat/themes#Demography
  skos:exactMatch http://id.vlaanderen.be/vrind/concept/demografie#id ;
.
http://ns.thedatatank.com/dcat/themes#Economy
  skos:exactMatch http://id.vlaanderen.be/vrind/concept/economie#id ;
.
http://ns.thedatatank.com/dcat/themes#Education
  skos:closeMatch http://id.vlaanderen.be/vrind/concept/onderwijs_en_vorming#id ;
.
http://ns.thedatatank.com/dcat/themes#Environment
  skos:closeMatch http://id.vlaanderen.be/vrind/concept/milieu#id ;
.
http://ns.thedatatank.com/dcat/themes#Financing
  skos:relatedMatch http://id.vlaanderen.be/vrind/concept/financien#id ;
.
http://ns.thedatatank.com/dcat/themes#Government
  skos:relatedMatch http://id.vlaanderen.be/vrind/concept/bestuurszaken#id ;
.
http://ns.thedatatank.com/dcat/themes#LivingHealthWelfare
  skos:narrowMatch http://id.vlaanderen.be/vrind/concept/gezondheid#id ;
  skos:narrowMatch http://id.vlaanderen.be/vrind/concept/welzijn#id ;
.
http://ns.thedatatank.com/dcat/themes#Media
  skos:exactMatch http://id.vlaanderen.be/vrind/concept/media#id ;
.
http://ns.thedatatank.com/dcat/themes#Mobility
  skos:exactMatch http://id.vlaanderen.be/vrind/concept/mobiliteit#id ;
.
http://ns.thedatatank.com/dcat/themes#Research
  skos:relatedMatch http://id.vlaanderen.be/vrind/concept/wetenschap_en_innovatie#id ;
.
http://ns.thedatatank.com/dcat/themes#Sport
  skos:exactMatch http://id.vlaanderen.be/vrind/concept/sport#id ;
.
http://ns.thedatatank.com/dcat/themes#Tourism
  skos:exactMatch http://id.vlaanderen.be/vrind/concept/toerisme#id ;
.
http://ns.thedatatank.com/dcat/themes#Work
  skos:relatedMatch http://id.vlaanderen.be/vrind/concept/arbeidsmarkt#id ;
.

**Comment by coreation** [comment]
Hi @PaulZH , are these the ones that need to be added or how do I interpret this dump? ;)

**Comment by ghost** [comment]
To be added.

Paul

> On 22 Jan 2015, at 14:31, Jan Vansteenlandt notifications@github.com wrote:
> 
> Hi @PaulZH https://github.com/PaulZH , are these the ones that need to be added or how do I interpret this dump? ;)
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/tdt/ns/issues/1#issuecomment-71020027.

Kind Regards,
Paul Hermans

---

ProXML bvba
Linked Data services
KBO: http://data.kbodata.be/organisation/0476_068_080#id http://data.kbodata.be/organisation/0476_068_080#id
(w) www.proxml.be http://www.proxml.be/
(e) paul@proxml.be mailto:paul@proxml.be
(tw)  @PaulZH
(t)  +32 15 23 00 76
(m) +32 473 66 03 20

OpenCube – Linked Open Statistical Data - http://opencube-project.eu/

**Comment by pietercolpaert** [comment]
Thanks! In the future, feel free to do this as a pull request (e.g., in browser: edit the file). Then you're also listed as an official contributor
